name: txt_reader
description: "A new Flutter project using GetX."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  file_picker: ^8.1.2
  styled_text: ^8.1.0
  getwidget: ^4.0.0
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 添加图片资源
  assets:
    - assets/illustrations/
    - assets/novels/

  # 字体配置
  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.otf
          weight: 700
