name: CI Check

on:
  push:
    branches:
      - main
      - uat
      - dev
      - release
  pull_request:
    branches:
      - main
      - uat
      - dev
      - release

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Install dependencies
        run: flutter pub get
