name: CI Check

on:
  push:
    branches:
      - main
      - uat
      - dev
      - release
  pull_request:
    branches:
      - main
      - uat
      - dev
      - release

env:
  FLUTTER_VERSION: "3.24.5"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
